-- 코드를 입력하세요
SELECT G.BOOK_ID, E.AUTHOR_NAME, DATE_FORMAT(G.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK AS G JOIN AUTHOR AS E ON G.AUTHOR_ID = E.AUTHOR_ID
WHERE G.CATEGORY LIKE '경제'
ORDER BY G.PUBLISHED_DATE ASC;